#!/bin/sh
# Generate runtime config from env vars (Railway / Docker friendly).
# Idempotent: only writes the file if it does not exist yet, so user edits
# in the mounted volume survive redeploys.

set -e

CONFIG_PATH="${OPENJARVIS_CONFIG:-/data/config.toml}"
CONFIG_DIR="$(dirname "$CONFIG_PATH")"
mkdir -p "$CONFIG_DIR"

# Bootstrap connector tokens from env. Re-extracts whenever the bundle hash
# changes so re-OAuth flows (e.g. expanded scopes) propagate without manual
# cleanup. The hash marker lives next to the tokens on the volume.
CONN_DIR="${CONFIG_DIR}/connectors"
if [ -n "${GOOGLE_OAUTH_BUNDLE_B64:-}" ]; then
  mkdir -p "$CONN_DIR"
  NEW_HASH=$(printf '%s' "$GOOGLE_OAUTH_BUNDLE_B64" | sha256sum | cut -c1-16)
  OLD_HASH=""
  [ -f "${CONN_DIR}/.bundle_hash" ] && OLD_HASH=$(cat "${CONN_DIR}/.bundle_hash")
  if [ "$NEW_HASH" != "$OLD_HASH" ]; then
    echo "[entrypoint] Extracting Google bundle (hash $NEW_HASH, was '$OLD_HASH')"
    printf '%s' "$GOOGLE_OAUTH_BUNDLE_B64" | base64 -d | tar xzf - -C "$CONN_DIR"
    chmod 600 "$CONN_DIR"/*.json 2>/dev/null || true
    printf '%s' "$NEW_HASH" > "${CONN_DIR}/.bundle_hash"
  else
    echo "[entrypoint] Google bundle unchanged (hash $NEW_HASH)"
  fi
fi

# Bump CONFIG_VERSION whenever the schema below changes — boots will then
# regenerate the file (preserving the volume but refreshing managed sections).
CONFIG_VERSION="5"
EXISTING_VERSION=""
if [ -f "$CONFIG_PATH" ]; then
  EXISTING_VERSION=$(grep -E '^# config-version =' "$CONFIG_PATH" | sed -E 's/^# config-version = "?([^"]+)"?/\1/' || true)
fi

if [ "$EXISTING_VERSION" != "$CONFIG_VERSION" ]; then
  echo "[entrypoint] Writing config v$CONFIG_VERSION to $CONFIG_PATH (was: '$EXISTING_VERSION')"
  cat > "$CONFIG_PATH" <<EOF
# config-version = "$CONFIG_VERSION"
# Auto-generated by entrypoint. Manual edits survive unless CONFIG_VERSION bumps.

[server]
host = "0.0.0.0"
agent = "${JARVIS_DEFAULT_AGENT:-native_react}"

[engine]
default = "cloud"

[agent]
default_agent = "${JARVIS_DEFAULT_AGENT:-native_react}"
max_turns = 8
tools = "${JARVIS_AGENT_TOOLS:-think,calculator,web_search,calendar_today,calendar_upcoming,calendar_create_event,gmail_search,gmail_unread,gmail_send,drive_search,tasks_list,tasks_create}"

[channel]
enabled = ${JARVIS_CHANNEL_ENABLED:-true}
default_channel = "${JARVIS_DEFAULT_CHANNEL:-telegram}"
default_agent = "${JARVIS_DEFAULT_AGENT:-native_react}"

[channel.telegram]
bot_token = ""
allowed_chat_ids = "${TELEGRAM_ALLOWED_CHAT_IDS:-}"
parse_mode = "Markdown"
EOF
else
  echo "[entrypoint] Reusing existing config v$CONFIG_VERSION at $CONFIG_PATH"
fi

export OPENJARVIS_CONFIG="$CONFIG_PATH"

exec jarvis serve --host 0.0.0.0 --port "${PORT:-8000}"
