#!/bin/sh
# Generate runtime config from env vars (Railway / Docker friendly).
# Idempotent: only writes the file if it does not exist yet, so user edits
# in the mounted volume survive redeploys.

set -e

CONFIG_PATH="${OPENJARVIS_CONFIG:-/data/config.toml}"
CONFIG_DIR="$(dirname "$CONFIG_PATH")"
mkdir -p "$CONFIG_DIR"

# Bootstrap connector tokens from env (one-shot — once written, can clear env).
CONN_DIR="${CONFIG_DIR}/connectors"
if [ -n "${GOOGLE_OAUTH_BUNDLE_B64:-}" ] && [ ! -f "${CONN_DIR}/google.json" ]; then
  echo "[entrypoint] Bootstrapping Google connector tokens from GOOGLE_OAUTH_BUNDLE_B64"
  mkdir -p "$CONN_DIR"
  printf '%s' "$GOOGLE_OAUTH_BUNDLE_B64" | base64 -d | tar xzf - -C "$CONN_DIR"
  chmod 600 "$CONN_DIR"/*.json 2>/dev/null || true
fi

# Bump CONFIG_VERSION whenever the schema below changes — boots will then
# regenerate the file (preserving the volume but refreshing managed sections).
CONFIG_VERSION="3"
EXISTING_VERSION=""
if [ -f "$CONFIG_PATH" ]; then
  EXISTING_VERSION=$(grep -E '^# config-version =' "$CONFIG_PATH" | sed -E 's/^# config-version = "?([^"]+)"?/\1/' || true)
fi

if [ "$EXISTING_VERSION" != "$CONFIG_VERSION" ]; then
  echo "[entrypoint] Writing config v$CONFIG_VERSION to $CONFIG_PATH (was: '$EXISTING_VERSION')"
  cat > "$CONFIG_PATH" <<EOF
# config-version = "$CONFIG_VERSION"
# Auto-generated by entrypoint. Manual edits survive unless CONFIG_VERSION bumps.

[server]
host = "0.0.0.0"

[engine]
default = "cloud"

[agent]
default_agent = "${JARVIS_DEFAULT_AGENT:-native_react}"
max_turns = 8
tools = "${JARVIS_AGENT_TOOLS:-think,calculator,web_search,calendar_today,calendar_upcoming,gmail_search,gmail_unread,drive_search,tasks_list}"

[channel]
enabled = ${JARVIS_CHANNEL_ENABLED:-true}
default_channel = "${JARVIS_DEFAULT_CHANNEL:-telegram}"
default_agent = "${JARVIS_DEFAULT_AGENT:-native_react}"

[channel.telegram]
bot_token = ""
allowed_chat_ids = "${TELEGRAM_ALLOWED_CHAT_IDS:-}"
parse_mode = "Markdown"
EOF
else
  echo "[entrypoint] Reusing existing config v$CONFIG_VERSION at $CONFIG_PATH"
fi

export OPENJARVIS_CONFIG="$CONFIG_PATH"

exec jarvis serve --host 0.0.0.0 --port "${PORT:-8000}"
